FROM golang:1.22.6 AS builder

WORKDIR /build

COPY go.mod go.sum .
RUN go mod download

COPY . .

# Установка инструментов тестирования
RUN go install github.com/onsi/ginkgo/v2/ginkgo
RUN go get github.com/onsi/gomega/...