env: local
token_ttl: 1h
jwt_secret: "6yTTCUa1FofsNtanut2sBTzNWsqMzO"
grpc:
  port: 44044
  timeout: 10h
postgres:
  user: "chat-app"
  database: "sso"
  password: "CHAT_APP"
  host: "127.0.0.1"
  port: 5454
