name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 1: Логин в Docker Registry (например, Docker Hub или GitHub Container Registry)
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY_HOST }}"

      # Шаг 2: Построить Docker-образ
      - name: Build Docker image
        run: |
          docker build -t sso:latest .
          docker tag sso:latest ${{ secrets.DOCKER_REGISTRY_HOST }}/sso:latest

      # Шаг 3: Запушить образ в Docker Registry
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY_HOST }}/sso:latest

  test:
    runs-on: self-hosted
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t sso:test -f Dockerfile.unittest .
      
      - name: Run Unit tests
        run: |
          docker run sso:test