name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY_HOST }}"

      - name: Build Docker image
        run: |
          docker build -t github_runner/sso:latest .
          docker tag github_runner/sso:latest ${{ secrets.DOCKER_REGISTRY_HOST }}/sso:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY_HOST }}/sso:latest

  test:
    runs-on: self-hosted
    needs: build
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t github_runner/sso:test -f Dockerfile.test .
      
      - name: Run Unit tests
        run: |
          docker run --rm github_runner/sso:test make test-unit

      # # Вот тут нужно отправить команду на запуск билда для проведения интеграционного тестирования
      # - name: Start Integration stand
      #   run: |
      #     ssh 

      # - name: Run Integration tests
      #   run: |
      #     docker run --rm -e github_runner/sso:test make test-integration